### ISSUE TITLE
Love the idea however AMD GPU Support?

### ISSUE THREAD

**Issue by MidnightKittenCat** [EngMarchG/Fsg-Pp#1]
Might be a good little look into, either way great project! just stumbled across it.

**Comment by EngMarchG** [comment]
Currently, the models run pretty fast even with just CPU enabled. However, we would definitely look into it later on. 

Usually, AMD is not supported due to its limited support even from Pytorch (only works on Linux). However, if you are keen on using gpu on AMD you can refer to the manual installation section and to the Pytorch docs, to install the suitable Pytorch version with pip.
